import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

function readUtf8(path: string): string {
  return readFileSync(path, 'utf8')
}

function assertIncludes(source: string, token: string, label: string) {
  assert.ok(source.includes(token), `${label} should include ${token}`)
}

const hubOverlay = readUtf8('godot-client/scripts/ui/main_city_hub_overlay.gd')
const main = readUtf8('godot-client/scripts/app/main.gd')
const actionAdapter = readUtf8('godot-client/scripts/app/adapters/slg_domain_action_adapter.gd')
const visualSmokeRunner = readUtf8('godot-client/tools/run_mainline_visual_smoke.py')
const troopReadModel = readUtf8('godot-client/data/ui/main_city_troop_formation_read_model.json')
const worldStore = readUtf8('godot-client/autoload/world_store.gd')

assertIncludes(hubOverlay, 'signal troop_formation_submit_requested(payload: Dictionary)', 'MainCityHubOverlay formal formation submit signal')
assertIncludes(hubOverlay, 'signal ai_troop_team_viewed(payload: Dictionary)', 'MainCityHubOverlay should emit silent AI team view context signal')
assertIncludes(hubOverlay, 'TroopGeneralSlotButton_', 'three general slot cards should be selectable buttons')
assertIncludes(hubOverlay, 'submit_selected_troop_formation_for_smoke', 'formal formation submit should stay on authority smoke path, not a fake foreground button')
assertIncludes(hubOverlay, '_build_troop_formation_submit_payload', 'formation detail should build formal submit payload')
assertIncludes(hubOverlay, 'ai_instruction_required', 'AI-owned formations should require chat/voice instruction instead of direct edit')
assertIncludes(hubOverlay, 'troopFormationSubmitMode', 'visual smoke summary should expose submit authority mode')
assertIncludes(hubOverlay, 'troopFormationSelectedTeamControllerLabel', 'visual smoke summary should expose selected team controller label')
assertIncludes(hubOverlay, 'troopFormationSelectedTeamBindSource', 'visual smoke summary should expose selected team formal bind source')
assertIncludes(hubOverlay, 'troopFormationSelectedTeamSourceUnitId', 'visual smoke summary should expose selected team source unit id')
assertIncludes(hubOverlay, 'troopFormationSelectedTeamSourceTeamId', 'visual smoke summary should expose selected team source team id')
assertIncludes(hubOverlay, 'troopFormationSelectedTeamSourceTeamIndex', 'visual smoke summary should expose selected team source team index')
assertIncludes(hubOverlay, 'troopFormationActionLocked', 'AI-owned formation actions should expose locked state')
assertIncludes(hubOverlay, 'troopFormationAiTeamContextPayload', 'AI-owned formation detail should expose invisible team context payload for silent chat context sync')
assertIncludes(hubOverlay, 'func set_troop_formation_read_model(next_read_model: Dictionary)', 'MainCityHubOverlay should accept backend troop formation read model injection')
assertIncludes(hubOverlay, 'troopFormationReadModelAuthoritySource', 'visual smoke summary should expose backend read model authority source')
assertIncludes(hubOverlay, 'AI队伍暂不可直接编组或征兵，请前往聊天频道。', 'AI-owned formation locked action should show a concise chat-channel hint')
assertIncludes(hubOverlay, 'front_mid_camp_to_map_visual_roles_v1', 'submit payload should preserve front/mid/camp map visual role order')
assertIncludes(hubOverlay, 'block_same_general_name_v1', 'submit payload should hard-block duplicate general names')
assertIncludes(hubOverlay, 'commercial_drill_ground_layered_slot_anchor_polish_v10', 'formation detail should use polished fullscreen drill-ground layout anchored to the background slot frames')
assertIncludes(hubOverlay, 'camp_mid_front_layered_hero_cards_grounded_manifest_units_v10', 'formation detail should align grounded manifest unit frames under reused hero cards on the background slots')
assertIncludes(hubOverlay, '_load_troop_unit_frame_textures', 'formation detail should load unit animation frames from the manifest')
assertIncludes(hubOverlay, 'manifest_direction_r_10_frame_timer_cycle_v1', 'formation detail should expose manifest-driven unit animation mode')
assertIncludes(hubOverlay, '"troopFormationSubmitButtonVisible": false', 'formation detail should not expose a fake submit button')
assertIncludes(hubOverlay, '["配置", "征兵"]', 'human-owned formation action row should expose config/recruit modes')
assertIncludes(hubOverlay, '_troop_slot_has_general', 'formation detail should distinguish empty slots from missing portrait assets')
assertIncludes(hubOverlay, 'TroopGeneralEmptySlotButton_', 'empty formation slots should render as empty slot cards')
assertIncludes(hubOverlay, 'empty_slot_card_no_unit_preview_v1', 'empty formation slots should explicitly hide troop unit previews')
assert.ok(!hubOverlay.includes('TroopSlotSquadGroundShadow'), 'formation detail should not restore black translucent ground pads under manifest unit sprites')

assertIncludes(actionAdapter, 'func request_deploy_general(hero_id: String, tile_id: String, co_hero_ids: Array = [], include_world: bool = true, options: Dictionary = {})', 'Godot deploy adapter should accept coHeroIds, optional lean response mode, and formal team ownership options')
assertIncludes(actionAdapter, '"coHeroIds": normalized_co_hero_ids', 'Godot deploy adapter should forward coHeroIds')
assertIncludes(actionAdapter, 'for optional_key in ["aiPlayerId", "teamId", "teamIndex"]', 'Godot deploy adapter should forward formal AI/team ownership fields')
assertIncludes(actionAdapter, 'func request_configure_deployed_unit_formation', 'Godot adapter should expose formal deployed unit formation reconfiguration')
assertIncludes(actionAdapter, 'configureDeployedUnitFormation', 'Godot adapter should call backend configureDeployedUnitFormation action')
assertIncludes(actionAdapter, 'func request_ai_context_focus(focus_id: String, extra_payload: Dictionary = {})', 'Godot AI context focus adapter should accept silent team context payload')

assertIncludes(main, '_on_main_city_troop_formation_submit_requested', 'main should handle hub formation submit signal')
assertIncludes(main, '_refresh_main_city_troop_formation_read_model', 'main should refresh formation read model from backend before troop tab verification')
assertIncludes(main, 'get_main_city_troop_formation_read_model', 'main should call backend formation read model endpoint through api client')
assertIncludes(main, 'var governor_player_id := AppConfig.player_name.strip_edges()', 'main should pass player name, not numeric seat id, to backend troop formation read model')
assertIncludes(main, 'click_action.begins_with("world_click_main_city_node_troop_")', 'mainline visual smoke should let troop click-action page assertions own hub visibility after the click')
assertIncludes(main, 'is_shell_component_contract_action', 'mainline visual smoke should let shell component contracts own their own visibility requirements')
assertIncludes(main, 'click_action == "world_left_troop_rail_component_contract"', 'left troop rail component contract should not require main-city hub visibility')
assertIncludes(main, 'WorldStore.set_ai_player_state(ai_player_id', 'main should mirror backend focus_team success into per-AI local state')
assertIncludes(main, 'request_deploy_general", hero_id, tile_id, co_hero_ids', 'main should submit formal three-hero formation to backend')
assertIncludes(main, 'troopFormationSelectedTeamBindSource', 'main smoke page summary should preserve selected team bind source')
assertIncludes(main, 'troopFormationSelectedTeamSourceUnitId', 'main smoke page summary should preserve selected team source unit id')
assertIncludes(main, 'deploy_options', 'main should pass formal team identity into deployReserveHero adapter options')
assertIncludes(main, '"teamIndex": int(payload.get("teamIndex", 0))', 'main should pass teamIndex into deployReserveHero payload options')
assertIncludes(main, '["100031", "100013", "100017"]', 'mainline submit smoke should expect Zhou Yu/Ma Chao/Zhuge Liang reserve formation')
assertIncludes(main, '_open_main_chat_overlay(ai_player_id)', 'AI formation edits should route to chat/voice instruction chain')
assertIncludes(main, 'main_city_troop_formation_submit_no_legacy_troop_panel_v1', 'player formation submit should not reopen the old long troop panel after authority success')
assertIncludes(main, 'world_click_main_city_node_troop_submit_player_formation', 'formal visual smoke should cover player formation submit')
assertIncludes(main, 'world_click_main_city_node_troop_configure_then_clear_slot', 'formal visual smoke should cover configure then clear slot flow')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_open_ai_fallback_team', 'formal visual smoke should cover AI fallback owner-label team')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_open_ai_fallback_team_context_focus', 'formal visual smoke should cover silent AI team context focus')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_open_ai_fallback_team_locked_config', 'formal visual smoke should cover locked AI config hint')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_open_ai_named_team', 'formal visual smoke should cover named AI owner-label team')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_open_ai_multi_team_second', 'formal visual smoke should cover single-AI multi-team second card binding')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_open_ai_multi_team_second_context_chat', 'formal visual smoke should cover single-AI multi-team focus context plus chat execution')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_multi_team_rail_stress', 'formal visual smoke should cover >3 team horizontal card rail stress')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_invalid_portrait_fallback', 'formal visual smoke should cover invalid portrait commercial fallback')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_empty_slots', 'formal visual smoke should cover empty formation slots')
assertIncludes(main, 'content_width > viewport_width', 'multi-team rail stress should verify horizontal overflow instead of card compression')
assertIncludes(main, 'total_count >= 5', 'multi-team rail stress should require at least five visible team cards')
assertIncludes(main, 'invalidPortraitFallbackOk', 'invalid portrait smoke should expose fallback visual result')
assertIncludes(main, 'emptySlotsOk', 'empty slot smoke should expose empty slot visual result')
assertIncludes(main, 'squad_preview_count == 0', 'empty slot smoke should verify no troop unit preview is rendered')
assertIncludes(main, 'troopFormationSelectedTeamSourceUnitId', 'single-AI multi-team smoke should assert source unit id')
assertIncludes(main, 'expectedSourceTeamId', 'single-AI multi-team smoke should assert the selected formal source team id')
assertIncludes(main, 'expectedTargetTeamSource', 'single-AI multi-team context chat smoke should assert silent context team source')
assertIncludes(main, 'send_ai_player_chat_message', 'single-AI multi-team context chat smoke should execute the existing chat channel API')
assertIncludes(main, 'world_click_main_city_node_troop_assign_preview_open_first_team_recruit_mode', 'formal visual smoke should verify recruit mode button')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_submit_player_formation', 'formal visual smoke runner should whitelist player formation submit')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_configure_then_clear_slot', 'formal visual smoke runner should whitelist configure then clear slot flow')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_open_ai_fallback_team', 'formal visual smoke runner should whitelist AI fallback owner-label team')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_open_ai_fallback_team_context_focus', 'formal visual smoke runner should whitelist silent AI team context focus')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_open_ai_fallback_team_locked_config', 'formal visual smoke runner should whitelist locked AI config hint')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_open_ai_named_team', 'formal visual smoke runner should whitelist named AI owner-label team')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_open_ai_multi_team_second', 'formal visual smoke runner should whitelist single-AI multi-team second card binding')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_open_ai_multi_team_second_context_chat', 'formal visual smoke runner should whitelist single-AI multi-team focus context plus chat execution')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_multi_team_rail_stress', 'formal visual smoke runner should whitelist >3 team card rail stress')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_invalid_portrait_fallback', 'formal visual smoke runner should whitelist invalid portrait fallback')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_empty_slots', 'formal visual smoke runner should whitelist empty formation slots')
assertIncludes(visualSmokeRunner, '"teamCount": 4', 'formal visual smoke runner should seed enough AI teams for >3 card rail stress')
assertIncludes(visualSmokeRunner, '"forceInvalidPortraitAssetKey": args.click_action == "world_click_main_city_node_troop_assign_preview_invalid_portrait_fallback"', 'formal visual smoke runner should seed invalid portrait keys through backend action')
assertIncludes(visualSmokeRunner, '"forceEmptyTeamSlots": args.click_action == "world_click_main_city_node_troop_assign_preview_empty_slots"', 'formal visual smoke runner should seed empty formation slots through backend action')
assertIncludes(visualSmokeRunner, 'seedMainCityTroopFormationMultiTeamFixture', 'formal visual smoke runner should seed single-AI multi-team backend fixture through world action')
assertIncludes(visualSmokeRunner, 'world_click_main_city_node_troop_assign_preview_open_first_team_recruit_mode', 'formal visual smoke runner should whitelist recruit mode')
assertIncludes(visualSmokeRunner, 'raw_sequence_frames_only', 'formation-page animation smoke should allow raw page sequence frames without map-unit closeup artifacts')

assertIncludes(readUtf8('godot-client/scripts/infra/http/backend_api_client.gd'), '/api/world/main-city/troop-formation', 'Godot backend client should expose formal troop formation read model endpoint')
assertIncludes(readUtf8('server/src/routes/world.ts'), 'handleMainCityTroopFormationReadModelRoute', 'backend route should expose formal troop formation read model handler')
assertIncludes(readUtf8('server/src/routes/world.ts'), 'seedMainCityTroopFormationMultiTeamFixtureAction', 'backend route should expose single-AI multi-team fixture action')
assertIncludes(readUtf8('server/src/routes/world.ts'), 'configureDeployedUnitFormationAction', 'backend route should expose deployed unit formation configure action')
assertIncludes(readUtf8('server/src/app.ts'), '/api/world/main-city/troop-formation', 'backend app should register formal troop formation read model route')
assertIncludes(readUtf8('server/src/application/world/mainCityTroopFormationReadModel.ts'), 'backend_ai_player_main_city_state_v1', 'backend formation read model should prove AI/main-city authority source')
const worldService = readUtf8('server/src/application/world/WorldService.ts')
assertIncludes(worldService, 'seedMainCityTroopFormationMultiTeamFixtureAction', 'WorldService should provide a formal single-AI multi-team smoke fixture')
assertIncludes(worldService, 'configureDeployedUnitFormationAction', 'WorldService should provide a formal deployed unit formation configure action')
assertIncludes(worldService, 'teamCount', 'WorldService multi-team fixture should support >3 team rail stress')
assertIncludes(worldService, 'forceInvalidPortraitAssetKey', 'WorldService multi-team fixture should support invalid portrait fallback smoke')
assertIncludes(worldService, 'forceEmptyTeamSlots', 'WorldService multi-team fixture should support empty formation slot smoke')
assertIncludes(readUtf8('shared/schemas/worldAction.ts'), 'teamCount: z.number().int().min(2).max(12).optional()', 'world action schema should allow bounded multi-team fixture count')
assertIncludes(readUtf8('shared/schemas/worldAction.ts'), 'forceInvalidPortraitAssetKey: z.boolean().optional()', 'world action schema should expose invalid portrait fallback fixture flag')
assertIncludes(readUtf8('shared/schemas/worldAction.ts'), 'forceEmptyTeamSlots: z.boolean().optional()', 'world action schema should expose empty formation slot fixture flag')
assertIncludes(readUtf8('shared/contracts/game/world.ts'), 'teamCount?: number', 'world action contract should expose bounded multi-team fixture count')
assertIncludes(readUtf8('shared/contracts/game/world.ts'), 'forceInvalidPortraitAssetKey?: boolean', 'world action contract should expose invalid portrait fallback fixture flag')
assertIncludes(readUtf8('shared/contracts/game/world.ts'), 'forceEmptyTeamSlots?: boolean', 'world action contract should expose empty formation slot fixture flag')
assertIncludes(worldStore, '"aiStateByPlayerId": {}', 'WorldStore should keep per-AI state map')
assertIncludes(worldStore, 'func get_ai_player_state(ai_player_id: String) -> Dictionary', 'WorldStore should expose per-AI state getter')
assertIncludes(worldStore, 'func set_ai_player_state(ai_player_id: String, state: Dictionary) -> void', 'WorldStore should expose per-AI state setter')

assertIncludes(troopReadModel, '"hero_id": "100017"', 'formal player slot should carry deployable Zhuge Liang hero id')
assertIncludes(troopReadModel, '"hero_id": "100013"', 'formal player slot should carry deployable Ma Chao hero id')
assertIncludes(troopReadModel, '"hero_id": "100031"', 'formal player front slot should use owned formal-pack Zhou Yu hero id')
assertIncludes(troopReadModel, 'formal_pack.portrait.zhou_yu_mature_chibi_v1', 'formal player front slot should use owned formal-pack portrait')
assertIncludes(troopReadModel, 'formal_pack.portrait.zhuge_liang_mature_beifa_v1', 'formal player camp slot should use owned formal-pack portrait')
assertIncludes(troopReadModel, 'formal_pack.portrait.ma_chao_mature_xiliang_retreat_v1', 'formal player mid slot should use owned formal-pack portrait')
assertIncludes(troopReadModel, 'unit_frames_manifest_v2_visual_types_direction_r_sequence_07', 'unit previews should come from the formal unit frame manifest')
assertIncludes(troopReadModel, 'infantry_ai_frames/r_07_infantry_ai_sheet_v1.png', 'infantry preview should use formal manifest infantry frame')
assertIncludes(troopReadModel, 'qibing_frames/r_07_map_qibing_0_7.png', 'cavalry preview should use formal manifest cavalry frame')
assertIncludes(troopReadModel, 'archer_ai_frames/r_07_archer_ai_sheet_v1.png', 'archer preview should use formal manifest archer frame')
assertIncludes(troopReadModel, '"ai_player_id": "ai_player_jihan_vanguard"', 'AI fallback owner-label team should be present in the read model')
assertIncludes(troopReadModel, '"aiPlayerName": "江东参谋AI"', 'named AI owner-label team should be present in the read model')
assert.ok(!troopReadModel.includes('drill_ground_unit_preview_'), 'read model should not reference deleted temporary drill-ground unit previews')
assert.ok(!troopReadModel.includes('"hero_id": "100036"'), 'formal player front slot should not use Sun Shangxiang after commercial redesign')
assertIncludes(readUtf8('shared/domain/scenario.ts'), "const playerReserveHeroIds = ['诸葛亮', '周瑜', '马超'].map(getHeroIdByName)", 'scenario reserve should keep formal submit deployable without Sun Shangxiang')

const portraitRegistry = readUtf8('godot-client/scripts/ui/portrait_asset_registry.gd')
assertIncludes(portraitRegistry, 'formal_pack_asset_runtime_lookup.preview.json', 'portrait registry should consume formal pack runtime lookup')
assertIncludes(portraitRegistry, 'portraitByAssetKey', 'portrait registry should resolve hero portraits through runtime lookup portraitByAssetKey')
assertIncludes(portraitRegistry, '_commercial_fallback_texture', 'portrait registry should provide a commercial fallback texture for missing assets')
assertIncludes(
  readUtf8('server/src/application/world/mainCityTroopFormationReadModel.ts'),
  'resolveFormalPackPortraitAssetKey',
  'backend read model should normalize formal deployed unit hero portraits before Godot renders them',
)

console.log('[main_city_troop_formation_godot_contract] all checks passed')
